dist: trusty
sudo: false

jobs:
  include:
    - name: Python 3.7 on Ubuntu Linux 18.04
      os: linux
      dist: bionic
      language: python
      python: '3.7'
    - name: Python 3.8 on Ubuntu Linux 18.04
      os: linux
      dist: bionic
      language: python
      python: '3.8'
    # See https://blog.travis-ci.com/2019-08-07-extensive-python-testing-on-travis-ci
    # for macos config peculiarities.
    - name: Python 3.7 on MacOS X (xcode 10.3)
      os: osx
      language: shell
      osx_image: xcode10.3  # Python 3.7
    - name: Python 3.7 on MacOS X (xcode 11.3)
      os: osx
      language: shell
      osx_image: xcode11.3  # Python 3.7.5
      

cache:
  directories:
  - $HOME/.cache/pip

install:
  # install miniconda
  #- deactivate
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - MINICONDA_PATH=/home/travis/miniconda
  - chmod +x miniconda.sh && ./miniconda.sh -b -p $MINICONDA_PATH
  - export PATH=$MINICONDA_PATH/bin:$PATH
  - conda update -y conda
  # create the testing environment
  - conda create -n testenv --yes pip
  - source activate testenv
  - conda install -y numpy scipy scikit-learn cython nose numba matplotlib pytest pytest-cov
  - pip install codecov
  - pip install .

script:
  - pytest -v --cov=skdim --pyargs skdim

after_success:
  - codecov
